spring:
  datasource:
    hikari:
      maximum-pool-size: 100 
database:
  username: root
  password: root
  host: localhost
  port: 3306
  dbname: datacenter
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
logging:
  config: classpath:log4j2-local.yml
