spring:
  datasource:
    hikari:
      maximum-pool-size: 100 
  redis: 
    # 服务器地址
    host: 43.138.158.87
    # 端口号
    prot: 6379
    # 数据库编号
    database: 0
    # 超时时间
    timeout: 50000
database:
  username: root
  password: root
  host: localhost
  port: 3306
  dbname: datacenter

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181

