spring:
  profiles: 
    # home | local   
    active: home
  datasource:
    name: external-data
    username: ${database.username}
    password: ${database.password}
    url: jdbc:mysql://${database.host}:${database.port}/${database.dbname}?useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 3600000
mybatis:
  mapper-locations:
  - classpath:com/jxzj/external/data/dao/*.xml
  type-aliases-package: com.jxzj.external.data.entity
 
logging: 
  config: classpath:log4j2.xml

  
#dubbo:
#  application:
#    id: external-data-provider
#    name: external-data-provider
#    qosEnable: false
#  protocol:
#    id: dubbo
#    name: dubbo
#    port: 22406
#    status: server
#    threads: 500
#  registry:
#    id: jxzj-registry
#  scan:
#    base-packages:
#    - com.jxzj.external.data.service
#  consumer:
#    check: false
#    timeout: 5000
